# length of media info string. If the length of the string exceeds this value,
# the text will scroll.
message_display_len: 20

# font index of polybar. This value should be 1 higher than the font value specified
# in the polybar config
font_index: 1

# update speed of the text in seconds
update_delay: 0.3

control_chars:
  play: ''
  pause: ''
  previous: ''
  next: ''

# icons to display as prefix for specific players
display_player_prefixes:
  default: ''
  specific:
    firefox: ''
    spotify: ''

# metadata fields based on mpris specification.
# See [mpris specification](https://www.freedesktop.org/wiki/Specifications/mpris-spec/metadata/) for more details
metadata_fields:
- xesam:title
- xesam:artist

metadata_seperator: '|'

# hide text when no player is available
hide_output: false
